'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
Imports System
Namespace WHSMailWeb

	Public Partial Class BasePage
		Protected form1 As System.Web.UI.HtmlControls.HtmlForm
	End Class
End Namespace
